pp_core_homepage:
    path:     /
    defaults: { _controller: PPCoreBundle:Core:index }

pp_core_newitem:
    path:     /resume/newitem/{itemType}
    defaults: { _controller: PPCoreBundle:Core:addItem }

pp_core_resume:
    path:     /resume
    defaults: { _controller: PPCoreBundle:Core:resume }

pp_core_contact:
    path:     /contact
    defaults: { _controller: PPCoreBundle:Core:contact }

pp_core_messages:
    path:     /messages
    defaults: { _controller: PPCoreBundle:Core:messages }

pp_core_portfolio:
    path:     /portfolio
    defaults: { _controller: PPCoreBundle:Core:portfolio }
