<?php

namespace PP\BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticles($page, $nbPerPage)
    {
    $query = $this->createQueryBuilder('a')
        ->orderBy('a.createdAt', 'DESC')
        ->getQuery()
    ;

    $query
        // On définit l'annonce à partir de laquelle commencer la liste
        ->setFirstResult(0) //($page * $nbPerPage)-1)
        // Ainsi que le nombre d'annonce à afficher sur une page
        ->setMaxResults($nbPerPage)
    ;
    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
    }
}
